### ISSUE TITLE
nodeinfo should collect software versions

### ISSUE THREAD

**Issue by pboothe** [m-lab/nodeinfo#12]
It seems silly to make a lot of datatypes like `kubelet-version` and `docker-version`. Instead, we should make a single script that spits out the versions of software that we care about, and then nodeinfo should run that script.

**Comment by nkinkade** [comment]
Since we are already capturing the OS version (/etc/os-release.txt) and kernel version (uname -a), and this may only leave kubelet and docker version, rather than creating a script in epoxy-images that nodeinfo runs (which is tedious and indirect) we may want to just consider adding a new entry to the nodeinfo config like:

```
  {
    Datatype: 'versions',
    Filename: 'versions.txt',
    Cmd: ['kubelet', '--version', ';', 'docker', '--version'],
  },
```

Can `Cmd` include a semicolon in the arg list?

**Comment by nkinkade** [comment]
Thinking about it more, I believe `Cmd` cannot accept `;` as an argument. In that case, then perhaps something like:

```
  Cmd: ['sh', '-c', 'kubelet --version; docker --version'],
```

**Comment by pboothe** [comment]
That would work, but it feels like fighting the system (that I wrote).

Instead, what we're seeing is a configuration option that isn't well-supported by the current syntax.  If you could configure this with JSON, how would you want that JSON to look?

Maybe
```
{
  Datatype: 'version',
  Cmds: [
   {
     Name: 'docker',
     Cmd: ['docker',  'version']
   },
   {
     Name: 'kubelet',
     Cmd: ['kubelet', '--version']
    }
  ]
}
```
or maybe some other syntax?

**Comment by nkinkade** [comment]
Just for the benefit of others reading this issue, I'll document the thinking I expressed to you on the M-Lab Open VC: my gut feeling is that the current config syntax has been meeting our needs and this most recent need can be satisfied by the current config format in a very concise manner. I'm not sure that now is the moment to refactor the config file when a command as basic as:

```
  Cmd: ['sh', '-c', 'kubelet --version; docker --version'],
```

... can meet our needs within the current system.

**Comment by pboothe** [comment]
For now, let's proceed with @nkinkade's insight. The longer term goal is #13
